replicaCount: 2

image:
  repository: nzsulehry/netflix
  tag: dev
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

resources: {}
