apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netflix.fullname" . }}
  labels:
    {{- include "netflix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "netflix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "netflix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: netflix-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
